name: Build MariDB LXC Image

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/build-mariadb.yml'
      - 'templates/mariadb.yml'
  schedule:
    - cron: '0 3 */1 * *'

jobs:
  init:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Get Application version
        id: get-app-version
        run: |
          DG=$(curl -s "https://hub.docker.com/v2/repositories/library/mariadb/tags/" | jq -r '.results[] | select(.name |contains("latest"))|.digest')
          echo "APP_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/library/mariadb/tags/"| jq --arg digest $DG -r '.results[] | (select(.digest |contains($digest))) | select(.name |test("^\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$"))| .name')" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{steps.get-app-version.outputs.APP_VERSION}}

  image-build:
    needs: init
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/mariadb.yml
      app_name: mariadb
      app_version: ${{needs.init.outputs.app_version}}
      app_ports: 3306
      description: MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system.
      categories: Database, SQL
      project_source: https://github.com/mariadb/server
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: ${{github.event.pull_request.base.ref}}
      is_merged: ${{github.event.pull_request.merged || github.event_name == 'schedule'}}
    secrets: inherit
