name: Build JupyterLab LXC Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/build-jupyterlab.yml'
      - 'templates/jupyterlab.yml.j2'
  schedule:
    - cron: '0 3 */1 * *'

jobs:
  init:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Get Application version
        id: get-app-version
        run: |
          echo "APP_VERSION=$(curl -s https://api.github.com/repos/jupyterlab/jupyterlab/releases/latest | jq -r '.tag_name' | sed -E 's/^v|V//')" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{steps.get-app-version.outputs.APP_VERSION}}

  image-build:
    needs: init
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/jupyterlab.yml.j2
      app_name: jupyterlab
      app_version: ${{needs.init.outputs.app_version}}
      app_ports: 8888
      description: JupyterLab is the latest web-based interactive development environment for notebooks, code, and data.
      categories: IDE, Python, Dev
      project_source: https://github.com/jupyterlab/jupyterlab
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: ${{github.event.pull_request.base.ref}}
      is_merged: ${{github.event.pull_request.merged || github.event_name == 'schedule'}}
    secrets: inherit
