name: Test Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - ".github/publish_build.hurl"
      - ".github/workflows/builder.yml"
      - ".github/workflows/build-tester.yml"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

  image-build:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/debian-test.yml
      branch_name: test
      is_merged: false
    secrets: inherit
