name: Test Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/publish_build.hurl'
      - '.github/workflows/builder.yml'
      - '.github/workflows/build-tester.yml'

jobs:
  image-build:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/debian-test.yml
      app_name: dummy_app
      app_version: '0.0.0'
      categories: test, dummy
      project_source: https://github.com/soubinan/homelab-lxc
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: test
      is_merged: false
    secrets: inherit
