name: Build Vault LXC Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/build-vault.yml'
      - 'templates/vault.yml'
  schedule:
    - cron: '0 3 */1 * *'

jobs:
  init:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Get Application version
        id: get-app-version
        run: |
          echo "APP_VERSION=$(curl -s https://api.github.com/repos/hashicorp/vault/releases/latest | jq -r '.tag_name' | sed -E 's/^v|V|.+@//')" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{steps.get-app-version.outputs.APP_VERSION}}

  image-build:
    needs: init
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/vault.yml
      app_name: vault
      app_version: ${{needs.init.outputs.app_version}}
      description: Vault is a free and source-available secrets management tool / secrets store.
      categories: Secrets management, Security
      project_source: https://github.com/hashicorp/vault
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: ${{github.event.pull_request.base.ref}}
      is_merged: ${{github.event.pull_request.merged || github.event_name == 'schedule'}}
    secrets: inherit
