name: Container Image Build and Sign

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev"]

env:
  PROJECT_URL: https://github.com/soubinan/homelab-lxc
  AUTHOR: https://github.com/soubinan
  VERSION: 1.0.1

jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64]
        release: ['bookworm']
    runs-on: ubuntu-latest

    steps:
      - name: Install Distrobuilder
        run: |
          apt update
          apt install -y golang-go debootstrap rsync gpg squashfs-tools git make
          mkdir -p $HOME/go/src/github.com/lxc/
          cd $HOME/go/src/github.com/lxc/
          git clone https://github.com/lxc/distrobuilder
          cd ./distrobuilder
          make
          cp $HOME/go/bin/distrobuilder /usr/bin/distrobuilder
          mkdir /output

      - name: Build Image
        if: github.event_name == 'pull_request'
        run: |
          pwd
          distrobuilder build-lxc templates/homarr.yaml -o image.architecture=${{ matrix.architecture }} -o image.release=${{ matrix.release }} -o image.variant=cloud -o source.url="http://ftp.us.debian.org/debian" /output

      - name: Publish Artefacts
        if: github.event_name == 'push'
        run: |
          mv /output/rootfs.tar.xz /output/homarr-$VERSION.rootfs.tar.xz
          mv /output/meta.tar.xz /output/homarr-$VERSION.meta.tar.xz
