name: Build Gitea LXC Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/build-gitea.yml'
      - 'templates/gitea.yml'
  schedule:
    - cron: '0 3 */1 * *'

jobs:
  init:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Get Application version
        id: get-app-version
        run: |
          echo "APP_VERSION=$(curl -s https://dl.gitea.com/gitea/version.json| jq -r '.latest.version' | sed -E 's/^v|V|.+@//')" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{steps.get-app-version.outputs.APP_VERSION}}

  image-build:
    needs: init
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/gitea.yml
      app_name: gitea
      app_version: ${{needs.init.outputs.app_version}}
      description: Git with a cup of tea! Painless self-hosted all-in-one software development service, including Git hosting, code review, team collaboration, package registry and CI/CD.
      categories: Git, CI CD, Dev
      project_source: https://github.com/go-gitea/gitea
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: ${{github.event.pull_request.base.ref}}
      is_merged: ${{github.event.pull_request.merged || github.event_name == 'schedule'}}
    secrets: inherit
