name: Build AdGuard LXC Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/build-adguard.yml'
      - 'templates/adguard.yml'
  schedule:
    - cron: '0 2 */1 * *'

jobs:
  init:
    if: github.event.action != 'closed' || (github.event.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Get Application version
        id: get-app-version
        run: |
          echo "APP_VERSION=$(curl -s https://github.com/AdguardTeam/AdGuardHome/releases/latest | jq -r '.tag_name' | sed -E 's/.*v|.*V|.+@//')" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{steps.get-app-version.outputs.APP_VERSION}}

  image-build:
    needs: init
    strategy:
      matrix:
        architectures:
          - amd64
    uses: ./.github/workflows/builder.yml
    with:
      config_path: templates/adguard.yml
      app_name: adguard
      app_version: ${{needs.init.outputs.app_version}}
      description: Network-wide ads & trackers blocking DNS server
      categories: DNS, Privacy
      project_source: https://github.com/AdguardTeam/AdGuardHome
      distribution: debian
      release: bookworm
      architecture: ${{matrix.architectures}}
      branch_name: ${{github.event.pull_request.base.ref}}
      is_merged: ${{github.event.pull_request.merged || github.event_name == 'schedule'}}
    secrets: inherit
